using System.ComponentModel.DataAnnotations;
using System.Reflection;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using VitaTrack.Core.Features.ServiceConnections;

namespace VitaTrack.Tests;

/// <summary>
/// The connect form's labels are generated by <c>asp-for</c> from the bind model's
/// display metadata, so the wording lives in attributes and is asserted here rather
/// than read off rendered HTML. Left to the property names, the labels would say
/// "BaseUrl" and "ApiKey" while the saved-state table and the field errors — the same
/// words the e2e spec selects on — say "Base URL" and "API key".
/// </summary>
[TestClass]
public class ServiceConnectionFormTests
{
    [TestMethod]
    public void ConnectForm_LabelsSayBaseUrlAndApiKeyLikeTheRestOfTheScreen()
    {
        Assert.AreEqual("Base URL", DisplayNameOf(nameof(ConnectServiceRequest.BaseUrl)));
        Assert.AreEqual("API key", DisplayNameOf(nameof(ConnectServiceRequest.ApiKey)));
    }

    [TestMethod]
    public void ConnectForm_EachErrorMessageStartsWithItsOwnLabel()
    {
        // Two copies of the same field's name must agree: the label a user reads
        // beside the input, and the message beside it when it is empty.
        Assert.IsTrue(
            RequiredMessageOf(nameof(ConnectServiceRequest.BaseUrl))
                .StartsWith(DisplayNameOf(nameof(ConnectServiceRequest.BaseUrl)), StringComparison.Ordinal),
            "a stripped field (\"Base URL: ---\") must name the field the way the label does");
        Assert.IsTrue(
            RequiredMessageOf(nameof(ConnectServiceRequest.ApiKey))
                .StartsWith(DisplayNameOf(nameof(ConnectServiceRequest.ApiKey)), StringComparison.Ordinal),
            "a stripped field (\"API key: ---\") must name the field the way the label does");
    }

    private static string DisplayNameOf(string property) =>
        typeof(ConnectServiceRequest).GetProperty(property)?.GetCustomAttribute<DisplayAttribute>()?.Name
        ?? property;

    private static string RequiredMessageOf(string property) =>
        typeof(ConnectServiceRequest).GetProperty(property)?.GetCustomAttribute<RequiredAttribute>()?.ErrorMessage
        ?? string.Empty;
}
