const { test, expect } = require('@playwright/test');
const { screenshot } = require('../helpers/screenshot');
const { startLlmStub, reserveClosedPort } = require('../helpers/llm-stub');

// The Settings page has two halves, and both are here. The first eight tests drive it
// with base URLs that do not answer: a connection saved through the form, a probe that
// could not confirm it, the model picker that follows, and a disconnect. That is the
// ordinary outcome for a provider with no /v1/models and the case the unverified
// wording exists for. The five after them drive the same page against a real listening
// socket (helpers/llm-stub.js) — the probe that verifies, the catalog it comes back
// with, the picker built from it, and the completion the enrichment flow makes.
//
// The stub stands in for the service the app dials, never for the app: the app is
// unmodified, its status handling and JSON parsing are real, and the request that
// arrives is recorded whole so a test can assert on the credential and the model
// settings that travelled with it. The earlier tests do hold app requests open with
// page.route and let the app answer them; one also lets the app's own router 404 a POST
// the form made, which is a real response rather than a written one. Neither writes the
// app's answer, which is the single forbidden act — see the no-mock rule in the root
// AGENTS.md for where the line sits and what the two legal shapes are.
//
// A limit worth naming: nothing here can assert "the app made no request at all", only
// "it made no request to this stub". The stub watches one port, so a request the app sent
// anywhere else would be invisible to it; every route to the network in LlmService passes
// the `connection is null` check first, which is what makes the assertion carry, and that
// check has no e2e mutation of its own because no app-side change reaches the request
// count without tripping the message assertion one line earlier.
//
// Serial, and not a style choice: there is at most one active connection by design,
// so these tests contend on a single row. Under fullyParallel they would demote
// each other's connection and fail for a reason that has nothing to do with the code.
//
// The labels below are generated by asp-for from the bind model's Display metadata
// (ConnectServiceRequest.BaseUrl -> "Base URL", .ApiKey -> "API key"). They are
// asserted in ServiceConnectionFormTests.ConnectForm_LabelsSayBaseUrlAndApiKeyLikeTheRestOfTheScreen,
// so a label change without a selector change fails a unit test, not this one.

// Holds every matching request open until releaseOne() is called, once per request.
// The rapid-click test needed one latch; the swap tests need a *second* latch on the
// same route, and a hold that never re-armed would make the second assertion vacuous —
// which is the exact failure mode these tests exist to catch. The optional responder
// still lets the app answer, so one helper covers "held open" and "held open, then sent
// somewhere real" — and what it must never do is WRITE the app's answer, which is the
// act the no-mock rule in the root AGENTS.md forbids. See the re-enable test below.
function holdRequests(page, pattern, respond = route => route.continue()) {
  const state = { held: 0, released: 0 };
  page.route(pattern, async route => {
    state.held++;
    while (state.released < state.held) await new Promise(resolve => setTimeout(resolve, 5));
    await respond(route);
  });
  return { held: () => state.held, releaseOne: () => { state.released++; } };
}

test.describe.serial('Service Connection', () => {
  test('should save a connection from the Settings page and show it after reload', async ({ page }, testInfo) => {
    // Arrive by clicking, not by goto: the nav item is the entry point under test.
    await page.goto('/');
    await page.getByRole('link', { name: 'Settings' }).click();
    await expect(page).toHaveURL(/\/ServiceConnection(\/Index)?$/);
    await expect(page.locator('h2')).toHaveText('Settings');
    await screenshot(page, testInfo, 'service-connection-empty');

    const baseUrl = 'https://api.example.com';
    const apiKey = 'sk-tracer-abcd1234';

    await page.getByLabel('Base URL').fill(baseUrl);
    await page.getByLabel('API key').fill(apiKey);
    await page.getByLabel('Model (optional)').fill('gpt-4o-mini');
    await page.getByRole('button', { name: 'Save connection' }).click();

    // The connect is an htmx POST, so there is no navigation: the state below arrived by
    // a swap, and the URL is unchanged throughout.
    await expect(page).toHaveURL(/\/ServiceConnection(\/Index)?$/);
    await expect(page.getByText('Saved connection')).toBeVisible();
    await expect(page.getByText(baseUrl, { exact: true })).toBeVisible();
    await expect(page.getByText('••••1234', { exact: true })).toBeVisible();
    // The badge, not a table row: it is the one place the state is rendered, so a test
    // that counted two or zero of these would know the rendering had forked.
    await expect(page.getByText('unverified', { exact: true })).toBeVisible();
    // And the words, because a badge alone does not tell a user *why* the connection is
    // unverified. The endpoint above does not implement /v1/models, which is the
    // ordinary case this wording is for — not a bad key. It does NOT say the connection
    // still works: that claim was removed in 139f03f, and the sibling test below pins
    // `enrich` absent in both directions, so putting it back here would contradict a
    // pin rather than merely stale prose.
    await expect(page.getByText('Could not confirm the connection.')).toBeVisible();
    // Documentation, not evidence: an <input> has no text content, so this counts zero
    // by construction and would count zero even if the key were rendered. The
    // load-bearing check is ServiceConnectionControllerTests's JsonContains walk over the
    // view model — the key is structurally unreachable from what the view is handed.
    await expect(page.getByText(apiKey, { exact: false })).toHaveCount(0);
    await screenshot(page, testInfo, 'service-connection-saved');

    // The round trip the tracer exists to prove: it survived a fresh read of the DB.
    await page.reload();
    await expect(page.getByText('Saved connection')).toBeVisible();
    await expect(page.getByText(baseUrl, { exact: true })).toBeVisible();
    await expect(page.getByText('••••1234', { exact: true })).toBeVisible();
    // The key is re-entered on every save, so the field comes back empty.
    await expect(page.getByLabel('API key')).toHaveValue('');
    // The saved values prefill the form, so a reconnect does not retype them.
    await expect(page.getByLabel('Base URL')).toHaveValue(baseUrl);
    await expect(page.getByLabel('Model (optional)')).toHaveValue('gpt-4o-mini');
    // A plain page load does not probe, so no warning is shown on top of the badge:
    // nobody asked a question on this page load. The badge carries the lasting truth.
    await expect(page.getByText('Could not confirm the connection.')).toHaveCount(0);
  });

  test('should reject a save with a blank URL and keep the connection unchanged', async ({ page }, testInfo) => {
    await page.goto('/ServiceConnection/Index');

    // A save of the valid values first, so the rejection has something to leave alone.
    const baseUrl = 'https://api.rejected.example.com';
    await page.getByLabel('Base URL').fill(baseUrl);
    await page.getByLabel('API key').fill('sk-reject-abcd9999');
    await page.getByRole('button', { name: 'Save connection' }).click();
    await expect(page.getByText(baseUrl, { exact: true })).toBeVisible();

    // Clearing the URL and resubmitting must not blank the stored connection. The error
    // is a field error on the form, so the swapped region has to carry the form for the
    // user to see it at all — which is the assertion, not just the wording.
    await page.getByLabel('Base URL').fill('');
    await page.getByLabel('API key').fill('sk-reject-abcd9999');
    await page.getByRole('button', { name: 'Save connection' }).click();

    await expect(page.getByText('Base URL is required.')).toBeVisible();
    await expect(page.getByText(baseUrl, { exact: true })).toBeVisible();
    await screenshot(page, testInfo, 'service-connection-rejected');

    await page.reload();
    await expect(page.getByText(baseUrl, { exact: true })).toBeVisible();
  });

  test('should save a model and reasoning effort from the picker, then disconnect', async ({ page }, testInfo) => {
    // Entered by clicking, like a user reaching Settings rather than by deep URL.
    await page.goto('/');
    await page.getByRole('link', { name: 'Settings' }).click();
    await expect(page.getByText('Saved connection')).toBeVisible();

    // Two model fields share this page, and their ids have to differ or the <label for>
    // association breaks for both: the connect form's is asp-for="Model" (id="Model"),
    // so the picker's is prefixed. Asserted on the *rendered* accessible names and ids,
    // not on the [Display] strings the form tests read, because the regression this pins
    // is in the markup — and with a duplicated id both getByLabel selectors retarget to
    // the same input, whose value then matches both expectations by luck.
    const connectModelField = page.getByLabel('Model (optional)');
    const pickerModelField = page.getByLabel('Model', { exact: true });
    await expect(connectModelField).toHaveAttribute('id', 'Model');
    await expect(pickerModelField).toHaveAttribute('id', 'picker-model');
    await expect(connectModelField).toHaveAccessibleName('Model (optional)');
    await expect(pickerModelField).toHaveAccessibleName('Model');

    // The picker came from a probe that listed nothing, so the model is free text. If a
    // future probe did list models this becomes a <select>, and the test says so by
    // failing on a select that has no free-text field.
    await expect(pickerModelField).toBeVisible();
    await pickerModelField.fill('gpt-4o');
    // The reasoning-effort vocabulary is rendered whole and there is nothing to
    // discover, so the six values are pinned as rendered. A count would not do: a
    // dropdown that quietly lost "xhigh" would still satisfy any assertion about how
    // many options there are, and "xhigh" is a value the providers accept.
    await expect(page.getByLabel('Reasoning effort').locator('option'))
      .toHaveText(['none', 'low', 'medium', 'high', 'xhigh', 'max']);
    await page.getByLabel('Reasoning effort').selectOption('high');
    await page.getByRole('button', { name: 'Save model' }).click();

    // A silent re-render would be indistinguishable from a no-op, so the swap says so.
    await expect(page.getByText('Model and reasoning effort saved.')).toBeVisible();
    await screenshot(page, testInfo, 'service-connection-model-saved');

    // The round trip: the choice is in the database, not just in the fragment. Both the
    // picker and the connect form read the same column, so both come back with it.
    await page.reload();
    await expect(page.getByLabel('Model (optional)')).toHaveValue('gpt-4o');
    await expect(page.getByLabel('Model', { exact: true })).toHaveValue('gpt-4o');
    await expect(page.getByLabel('Reasoning effort')).toHaveValue('high');

    // One more save, so the Disconnect form below is a form a *swap* delivered rather
    // than one this page load rendered. The reload above is the reason this step exists:
    // without a swap immediately before the click, a confirm hook bound once at page load
    // would be attached to exactly the right form and the test would pass with it broken.
    await page.getByLabel('Reasoning effort').selectOption('low');
    await page.getByRole('button', { name: 'Save model' }).click();
    await expect(page.getByText('Model and reasoning effort saved.')).toBeVisible();

    // Disconnect asks first, and the assertion is that asking *happened*: the first click
    // must leave the connection standing, because a confirm hook that is not attached to
    // the swapped-in form deletes with no dialog at all. A handler that only accepted
    // could not tell the two apart, since the no-dialog case deletes anyway — so the
    // dismissal is the discriminating step and the acceptance is the one after it.
    let asked = [];
    const dismiss = dialog => { asked.push(dialog.message()); dialog.dismiss(); };
    page.once('dialog', dismiss);
    await page.getByRole('button', { name: 'Disconnect' }).click();

    await expect(page.getByText('Saved connection')).toBeVisible();
    expect(asked).toHaveLength(1);
    expect(asked[0]).toContain('Disconnect this service?');

    // Having refused it, the user changes their mind: the same form, asked again.
    asked = [];
    page.once('dialog', dialog => { asked.push(dialog.message()); dialog.accept(); });
    await page.getByRole('button', { name: 'Disconnect' }).click();
    await expect(page.getByText('Saved connection')).toHaveCount(0);
    await expect(page.getByText('Connect a service')).toBeVisible();
  });

  test('should show the connection state on the page enrichment happens from', async ({ page }, testInfo) => {
    // A connection of its own: the test above disconnected the last one, and this is
    // about what the Enrich flow shows when there is something to show.
    await page.goto('/ServiceConnection/Index');
    await page.getByLabel('Base URL').fill('https://api.badge.example.com');
    await page.getByLabel('API key').fill('sk-badge-abcd4321');
    await page.getByRole('button', { name: 'Save connection' }).click();
    await expect(page.getByText('unverified', { exact: true })).toBeVisible();

    // The Enrich flow is where a user is about to spend a request. An unverified
    // connection is perfectly usable, so a failed probe produces no error anywhere — and
    // without the badge here the user would enrich with a service nobody ever confirmed
    // and nothing on the screen would say so.
    //
    // Arrive at the nutrient editor by clicking a row's own link, so no id is hardcoded
    // (AGENTS.md). "Edit Nutrient Breakdown" is the page that renders the enrichment
    // editor; the "Nutrients" row button goes to a different view with no badge on it.
    await page.getByRole('link', { name: 'Supplements' }).click();
    await page.locator('tbody tr').first().getByRole('link', { name: 'Edit' }).click();
    await page.getByRole('link', { name: 'Edit Nutrient Breakdown' }).click();

    await expect(page.getByRole('heading', { name: /Nutrients for/ })).toBeVisible();
    const badge = page.getByText('unverified', { exact: true });
    await expect(badge).toBeVisible();
    // The sentence behind the word, pinned here rather than only on Settings. The note in
    // _Unverified.cshtml is per-response and gone on the next load, so on this page the
    // `title` is the ONLY statement of what "unverified" means — which is why its wording
    // has to be true on its own terms. It used to say "Enrichment can still work — the
    // endpoint may simply not offer a model list", which is false for a base URL that
    // already carried a version segment: the completion posts to /v1/v1/chat/completions,
    // 404s, and no nutrient row is ever written. The two clauses below are the ones that
    // revert fails on, and both are the causes the old wording denied rather than named.
    // TD-022 records that a `title` is hover-only and unreachably so; that gap is a
    // separate open question about the *shape* and this assertion settles nothing about it.
    await expect(badge).toHaveAttribute('title', /a base URL it does not serve/);
    await expect(badge).toHaveAttribute('title', /a rejected key/);
    await screenshot(page, testInfo, 'service-connection-badge-on-enrich-flow');
  });

  test('should disable the submit button while the connect is in flight', async ({ page }) => {
    // DESIGN.md: "HTMX forms must disable their submit button while a request is in flight
    // and re-enable on response". The request is held open so the disabled state is
    // observed rather than raced past — without the hold the guard would have finished
    // before the assertion ran, and this would pass with the guard deleted. The re-enable
    // half is pinned by the next test, which is the only shape in which it can fail.
    const held = holdRequests(page, '**/ServiceConnection/Connect');

    await page.goto('/ServiceConnection/Index');
    await page.getByLabel('Base URL').fill('https://api.slow.example.com');
    await page.getByLabel('API key').fill('sk-slow-abcd1234');

    const save = page.getByRole('button', { name: 'Save connection' });
    await save.click();
    await expect(save).toBeDisabled();

    held.releaseOne();
    await expect(page.getByText('Saved connection')).toBeVisible();
    // Not asserted here: `expect(save).toBeEnabled()`. The swap hands back a fresh
    // enabled button, so that assertion passes with the re-enable deleted. The test
    // below is where the re-enable is load-bearing.
  });

  test('should guard the submit button again after a swap replaced the form', async ({ page }) => {
    // The line service-connection.js's own header names as the failure it exists to
    // prevent. The guard is bound per form, and every connect swaps a fresh form into
    // #connection-state, so a guard bound once at load leaves the second submit on this
    // page with no protection at all. Deleting the htmx:afterSwap re-arm is what makes
    // the second assertion below fail.
    const held = holdRequests(page, '**/ServiceConnection/Connect');
    const save = page.getByRole('button', { name: 'Save connection' });

    await page.goto('/ServiceConnection/Index');
    await page.getByLabel('Base URL').fill('https://api.reguard.example.com');
    await page.getByLabel('API key').fill('sk-reguard-abcd1234');
    await save.click();
    await expect(save).toBeDisabled();
    held.releaseOne();
    await expect(page.getByText('Saved connection')).toBeVisible();

    // The second submit, on the form that swap delivered. The key is re-entered because
    // the saved state never carries it.
    await page.getByLabel('API key').fill('sk-reguard-abcd5678');
    await save.click();
    await expect(save).toBeDisabled();

    expect(held.held()).toBe(2);
    held.releaseOne();
    // The form came back empty, which is the swap having happened a second time.
    await expect(page.getByLabel('API key')).toHaveValue('');
  });

  test('should re-enable the submit button when the response is not swapped in', async ({ page }) => {
    // The other half of the DESIGN.md sentence, in the only shape where it can fail. On a
    // successful connect the response replaces the form, so the button that comes back is
    // a new one and "is it enabled?" proves nothing. A response htmx does not swap in
    // leaves the element asserted on below as the one that was disabled — marked here so
    // the test itself says so, since that is the whole reason it exists.
    //
    // The response is a REAL one. htmx's responseHandling leaves 4xx and 5xx unswapped
    // (htmx 2.0.4's defaults), so letting the app's own POST continue to a path its
    // router does not serve produces exactly the state this test is for — and it is the
    // running application that produces it. The alternative, which this test used to do,
    // was `route.fulfill({status: 500})`, which is the app's answer written by the test
    // and is the one act the no-mock rule forbids on an app endpoint. There is no real 500
    // to reach here: a rejected connect answers 200 with field errors on the form, and
    // antiforgery fails a request the rendered form cannot make, so a 404 from the app's
    // own router is the honest substitute for a fabricated failure rather than a weaker
    // one. `continue` still runs the app: the request leaves the browser, the response
    // comes back, and the assertions are on what the UI did with it.
    const toUnroutedPath = route => {
      const url = new URL(route.request().url());
      url.pathname = '/__no-such-endpoint__';
      return route.continue({ url: url.toString() });
    };

    const held = holdRequests(page, '**/ServiceConnection/Connect', toUnroutedPath);

    await page.goto('/ServiceConnection/Index');
    await page.getByLabel('Base URL').fill('https://api.broken.example.com');
    await page.getByLabel('API key').fill('sk-broken-abcd1234');

    const save = page.getByRole('button', { name: 'Save connection' });
    await save.click();
    await expect(save).toBeDisabled();
    await save.evaluate(button => { button.setAttribute('data-in-flight-marker', 'set'); });

    held.releaseOne();
    await expect(save).toBeEnabled();
    await expect(save).toHaveAttribute('data-in-flight-marker', 'set');
    // The marker surviving is the point: htmx does not swap a 404, so this is the same
    // element that went disabled, and "enabled" is the guard's re-enable rather than a
    // replacement. (The earlier tests in this serial run leave a connection saved, so the
    // claim to check is that *this* one was not saved — no action ran, so there was
    // nothing to save; the table still shows the previous URL, and the form still holds
    // what was typed.)
    await expect(page.getByText('https://api.broken.example.com', { exact: true })).toHaveCount(0);
    await expect(page.getByLabel('Base URL')).toHaveValue('https://api.broken.example.com');
  });

  test('should save a model with htmx blocked, and land on a page that says so', async ({ page }, testInfo) => {
    // Progressive enhancement, at the only level that can see it. htmx never loads, so
    // hx-post is inert and both forms have to work as plain form posts. The picker is
    // the half that did not: a form carrying hx-post and no asp-action/method falls back
    // to a GET of the current URL, which discards the choice with no error and leaves
    // the page looking exactly like a no-op.
    await page.route('**/lib/htmx/**', route => route.abort());

    // The test has to establish that htmx really is absent, or it passes just as well
    // with htmx working — the assertions below hold either way, because an enhanced
    // submit also saves the model. Without this, a mutation that removed the route
    // abort would leave the test green and it would be pinning nothing.
    await page.goto('/ServiceConnection/Index');
    expect(await page.evaluate(() => typeof window.htmx)).toBe('undefined');

    // A real form post navigates the document; an htmx post does not. Counting main-frame
    // navigations is how "the browser submitted this itself" is told apart from "htmx
    // submitted it and swapped a fragment in" — which is the whole difference between a
    // working enhancement and a silently discarded choice.
    let navigations = 0;
    page.on('framenavigated', frame => { if (frame === page.mainFrame()) navigations++; });

    await page.getByLabel('Base URL').fill('https://api.nohtmx.example.com');
    await page.getByLabel('API key').fill('sk-nohtmx-abcd1234');
    // The saved model, so that a picker which fails to save has something to be wrong
    // about: the assertion below is a change from gpt-4o-mini to gpt-4o.
    await page.getByLabel('Model (optional)').fill('gpt-4o-mini');
    await page.getByRole('button', { name: 'Save connection' }).click();

    // A real navigation, not a swap: the controller redirected, which is the whole
    // point of the branch under test.
    await expect(page).toHaveURL(/\/ServiceConnection(\/Index)?$/);
    await expect(page.getByText('https://api.nohtmx.example.com', { exact: true })).toBeVisible();
    await expect(page.getByLabel('Model (optional)')).toHaveValue('gpt-4o-mini');
    expect(navigations).toBeGreaterThan(0);

    await page.getByLabel('Model', { exact: true }).fill('gpt-4o');
    await page.getByLabel('Reasoning effort').selectOption('high');
    const before = navigations;
    await page.getByRole('button', { name: 'Save model' }).click();

    await expect(page).toHaveURL(/\/ServiceConnection(\/Index)?$/);
    expect(navigations).toBeGreaterThan(before);
    await expect(page.getByLabel('Model (optional)')).toHaveValue('gpt-4o');
    await expect(page.getByLabel('Model', { exact: true })).toHaveValue('gpt-4o');
    await expect(page.getByLabel('Reasoning effort')).toHaveValue('high');
    await screenshot(page, testInfo, 'service-connection-no-htmx');
  });

  // ── The verified half, against a real service ──────────────────────────────────
  // One stub per test, closed after it whatever happened. A describe-level variable
  // because afterEach is the only hook that also runs after a failing test, and a stub
  // left listening would hold its port — and the app's pooled keep-alive sockets to it
  // — for the rest of the run.
  let stub = null;
  test.afterEach(async () => {
    if (stub) await stub.close();
    stub = null;
  });

  async function startStub(options) {
    stub = await startLlmStub(options);
    return stub;
  }

  // Connects through the form the way a user does, and waits for the badge that says
  // what the probe concluded. Every test below needs this connect, and none of them
  // care how it was made — the badge is the app's own answer, read from the page.
  async function connectViaForm(page, baseUrl, apiKey, expectedBadge) {
    await page.getByLabel('Base URL').fill(baseUrl);
    await page.getByLabel('API key').fill(apiKey);
    await page.getByRole('button', { name: 'Save connection' }).click();
    await expect(page.locator('#connection-state .badge')).toHaveText(expectedBadge);
  }

  // The app's scraper User-Agent, repeated here so the question below is asked as nearly
  // as possible the way the app will ask it. A page that answers these two callers
  // differently is a real possibility and is named at the skip; a page that answers only
  // one of them because of the UA is a third-party accident, not a product one, so
  // matching it removes the largest single source of a false red.
  const ScraperUserAgent = 'VitaTrack/1.0 (supplement tracker)';

  // Whether THIS MACHINE can fetch a public HTTPS page — asked from the Playwright
  // worker process, over Node's own fetch, before any page is opened and with the app
  // nowhere in the request path.
  //
  // Why not the app's own answer: because the two questions are different, and this test
  // got them confused. "Can this machine reach a public page?" is about the environment
  // and is the only thing a skip is allowed to report. "Did the app scrape it?" is the
  // thing under test. Reading the app's verdict to decide the skip meant a product
  // failure reported itself as an environment fault — removing `?? document.Body` from
  // HtmlScraperService.CleanHtml, so the page fetched fine and extracted to nothing,
  // turned this test SKIPPED rather than red. A gate that reports the wrong thing is
  // worse than no gate: the suite stayed green over a broken scraper.
  async function pageIsReachable(url) {
    try {
      const response = await fetch(url, {
        headers: { 'User-Agent': ScraperUserAgent },
        signal: AbortSignal.timeout(10000),
      });
      return response.ok && (await response.text()).trim().length > 0;
    } catch {
      return false;
    }
  }

  test('should verify a connection against a service that lists its models, and pick one of them', async ({ page }, testInfo) => {
    const service = await startStub();
    const apiKey = 'sk-stub-verify-1234';

    await page.goto('/ServiceConnection/Index');
    await connectViaForm(page, service.baseUrl, apiKey, 'verified');

    // The badge, and the two things that must NOT be here with it. `exact` is what
    // tells "verified" from "unverified" — a substring match on the first would be
    // satisfied by the second, so the pair is the assertion and neither is alone.
    await expect(page.getByText('unverified', { exact: true })).toHaveCount(0);
    // The sentence behind the word, in the verified direction, so the attribute is pinned
    // as a whole rather than only in its unverified half: one partial renders both from
    // the same ternary, and a refactor of that ternary would otherwise only ever be
    // caught on the branch the enrichment pages show. The unverified half is pinned on the
    // enrichment page above, which is the one place it is the *only* statement there is.
    const badge = page.locator('#connection-state .badge');
    await expect(badge).toHaveText('verified');
    await expect(badge).toHaveAttribute('title', /answered the model-list test with this key/);
    // The unverified note is per-response: this response answers a probe, and that
    // probe verified, so there is nothing to explain about a free-text field.
    await expect(page.getByText('Could not confirm the connection.')).toHaveCount(0);
    await expect(page.getByText(service.baseUrl, { exact: true })).toBeVisible();
    await expect(page.getByText('••••1234', { exact: true })).toBeVisible();

    // The catalog the service listed, offered as a choice. The rendered option texts
    // in order — not a count, which a dropdown that lost 'stub-model-b' would satisfy.
    // These ids exist nowhere else in the app, so the only way they appear here is if
    // they came back on the wire.
    await expect(page.getByLabel('Model', { exact: true }).locator('option'))
      .toHaveText(['stub-model-a', 'stub-model-b']);

    // The probe really left the process, and carried the key the user typed rather than
    // one the test made up. This is what a real socket buys over a badge: the badge
    // could be green because the app believed something, and only the recorded request
    // shows what was asked, where, and with which credential.
    const probes = service.requests.filter(request => request.method === 'GET');
    expect(probes).toHaveLength(1);
    expect(probes[0].path).toBe('/v1/models');
    expect(probes[0].headers.authorization).toBe(`Bearer ${apiKey}`);

    // The raw key must not be anywhere in the document this swap produced — attributes
    // included, which is why this reads the HTML rather than counting text matches (an
    // <input> has no text, so a text count is zero by construction and would stay zero
    // even if the key were rendered). Scoped to the saved path on purpose: on a
    // *rejected* connect the key is what the user just typed into that field, and
    // showing it back is the redisplay behaviour, not a leak.
    expect(await page.content()).not.toContain(apiKey);
    await screenshot(page, testInfo, 'service-connection-verified');
  });

  test('should probe the same path for either form of the base URL trailing slash', async ({ page }) => {
    // ServiceEndpoint promises the two slash forms collapse to one URI, and a user types
    // both — a pasted gateway URL usually arrives with its trailing slash. A
    // form-sensitive combine would send "//v1/models" to one and "/v1/models" to the
    // other, and the failure would depend on the typo.
    //
    // The two forms are the origin itself and the origin with a slash, which is the
    // ambiguity that reaches the served path. A base URL carrying its own "/v1" is a
    // different question and not this test: the app appends its own "v1/models", so that
    // base asks for "/v1/v1/models" and the stub answers 404. The first draft of this
    // test used that base and failed on an unverified badge — which is the stub's 404
    // doing its job, and the reason the negative case below is a real observation
    // rather than an assumption.
    const service = await startStub();
    const apiKey = 'sk-stub-slash-1234';

    await page.goto('/ServiceConnection/Index');
    for (const baseUrl of [service.baseUrl, `${service.baseUrl}/`]) {
      await connectViaForm(page, baseUrl, apiKey, 'verified');
      // The user-visible half of the promise too: the same two models, in the same
      // order, from a base URL that differs only in one character.
      await expect(page.getByLabel('Model', { exact: true }).locator('option'))
        .toHaveText(['stub-model-a', 'stub-model-b']);
    }

    // Both requests, exactly, in order, and neither of them doubled or truncated. The
    // stub answers 404 for a path it does not serve, so a wrong URI would have shown
    // up as an unverified badge above rather than as a silently accepted 404.
    expect(service.requests.map(request => request.path)).toEqual(['/v1/models', '/v1/models']);
  });

  test('should leave a connection unverified when the service answers with nothing usable, and still save it', async ({ page }, testInfo) => {
    // Three answers that are not a model list, and the state each one has to produce.
    // Without them the suite proves only that a 200 verifies, which a stub answering
    // 200 to everything would also satisfy.
    const service = await startStub({ models: [] });

    await page.goto('/ServiceConnection/Index');

    // (a) A success status carrying no catalog. The strongest of the three, because the
    // status says yes: only the body can make this unverified, and the request count
    // proves the 200 really came back rather than the probe never having been sent.
    await connectViaForm(page, service.baseUrl, 'sk-stub-empty-1234', 'unverified');
    expect(service.requests).toHaveLength(1);
    expect(service.requests[0].path).toBe('/v1/models');
    await expect(page.getByText('Could not confirm the connection.')).toBeVisible();
    await expect(page.getByText(service.baseUrl, { exact: true })).toBeVisible();
    // The picker came from a probe that listed nothing, so the model is free text — and
    // the note that explains it is the other half of this state. Its wording is pinned
    // because it was wrong twice: it said the connection is "saved and usable either way",
    // and for a base URL that already carried a version segment the completion posts to
    // /v1/v1/chat/completions, 404s, and no nutrient row is written. The replacement then
    // over-corrected to "enrichment will fail on any of the three", which is false for the
    // first of them — see the negative assertion below. The badge's own `title` is pinned
    // on the enrichment page in the test above, which is the one place it is the *only*
    // statement there is.
    // Scoped to the swap target rather than the page: the note is a child of
    // #connection-state and nothing else on this page is a warning (the form's validation
    // summary is .alert-danger), so this resolves to exactly the partial under test.
    const unverifiedNote = page.locator('#connection-state .alert-warning');
    // The two causes the old wording denied, so reverting to it turns this red...
    await expect(unverifiedNote).toContainText('a base URL your service does not serve');
    await expect(unverifiedNote).toContainText('a key it rejected');
    // ...and the clause that is the point of naming them. Without it the note would name
    // three causes and promise nothing, which is not the same sentence: what is true of
    // all three is that they cannot be told apart from here, and that is what makes the
    // note diagnostic rather than a reassurance.
    await expect(unverifiedNote).toContainText('look exactly the same from here');
    // And the note must say nothing at all about enrichment, in EITHER direction — the
    // false claim was false in both. "Enrichment will fail" is wrong for the first cause,
    // and the stub in this test is the counterexample: llm-stub.js:76 serves
    // /v1/chat/completions unconditionally, so this very case (a) is a live working
    // connection carrying the note. "Enrichment can still work" is wrong for a base URL
    // that already carried a version segment. So the pinned property is the absence of the
    // claim, not one particular wording of it.
    await expect(unverifiedNote).not.toContainText(/enrich/i);
    // Free text, not an empty dropdown — the state a verified badge above an empty
    // picker would contradict. tagName is the discriminator that survives either one.
    await expect(page.locator('#picker-model')).toHaveJSProperty('tagName', 'INPUT');

    // (b) A path the service does not serve. The app asked for
    // {BaseUrl}/v1/models and got a 404, so the recorded path is the assertion: it
    // says the probe was issued, and to where.
    await connectViaForm(page, `${service.baseUrl}/elsewhere`, 'sk-stub-404-1234', 'unverified');
    expect(service.requests.at(-1).path).toBe('/elsewhere/v1/models');
    // And it was the 404 that decided it, not an absent probe: the only request to
    // the served path is the one from (a).
    expect(service.requests.filter(request => request.path === '/v1/models')).toHaveLength(1);
    await expect(page.getByText(`${service.baseUrl}/elsewhere`, { exact: true })).toBeVisible();

    // (c) Nothing listening at all — a refused connection rather than an unhappy one.
    // A failed probe is not a failed connect, and the connection is still saved. The
    // count not moving is the assertion: there was nowhere to send a request, so none
    // was recorded. (The same rendering for a host that does not resolve is already
    // pinned by the first test in this file; what is new here is the transport.)
    const deadPort = await reserveClosedPort();
    await connectViaForm(page, `http://127.0.0.1:${deadPort}`, 'sk-stub-dead-1234', 'unverified');
    expect(service.requests).toHaveLength(2);
    await expect(page.getByText(`http://127.0.0.1:${deadPort}`, { exact: true })).toBeVisible();
    await expect(page.getByText('Could not confirm the connection.')).toBeVisible();
    await screenshot(page, testInfo, 'service-connection-unverified-answers');
  });

  test('should refuse an enrich with no connection at all, and name Settings as the fix', async ({ page }, testInfo) => {
    // The stub is running and is *not* asked for anything. That is the assertion: with
    // no connection there is no service to enrich with, so the app must say so in
    // words before it spends a request — and a refusal that silently did nothing else
    // would look identical from the page unless the request count is read.
    const service = await startStub();

    await page.goto('/ServiceConnection/Index');
    // The previous test left a connection saved; this one starts from none, which is
    // the only state in which the message below is reachable.
    page.once('dialog', dialog => dialog.accept());
    await page.getByRole('button', { name: 'Disconnect' }).click();
    await expect(page.getByText('Connect a service')).toBeVisible();

    // Arrive by clicking, and reach the editor the way a user does: the nav, then the
    // page's own create button. No deep URL, so the path a user has is one that works.
    await page.getByRole('link', { name: 'Supplements' }).click();
    await page.getByRole('link', { name: 'Add New Supplement' }).click();

    await page.fill('input[name="Name"]', 'Stub Enrich Refusal');
    await page.fill('input[name="Brand"]', 'StubBrand');
    await page.fill('input[name="DailyDose"]', '1 capsule');
    // A real public page, because the refusal has to be reached *before* anything is
    // fetched: if it were ever fetched first, this test would start depending on the
    // internet to prove something about the app.
    await page.fill('input[name="ManufacturerUrl"]', 'https://example.com/');
    await page.click('button#enrich-btn');

    // The refusal names Settings, which is the one thing a user can act on, and says it
    // is not the model they are missing — the two messages are separate for that reason.
    // .first() because toContainText respects strict mode and throws on a locator that
    // resolves to more than one; a swap that ever rendered two notes should not take this
    // test down with a Playwright error instead of a statement about the app. Same reason
    // as the .first() in the last test, and this line had been left out of it.
    await expect(page.locator('.alert-info').first()).toContainText('Add one in Settings');
    await expect(page.locator('#nutrients-table .empty-row')).toBeVisible();
    // Nothing was asked of the service, and no badge is drawn either: with no
    // connection there is no state to report.
    //
    // Scoped to the editor region rather than to `span.badge` page-wide. The claim is
    // about the connection badge, and a page-wide count is broader than the claim: any
    // unrelated badge Bootstrap or a future field put on the Create page would fail this
    // assertion for a reason that has nothing to do with the connection. The two pages
    // that carry the container are Supplement/Create.cshtml:68 and
    // Supplement/EditNutrients.cshtml:8 (the container is the whole page there), both of
    // which render _NutrientEditor.cshtml:15, where this component appears.
    //
    // Review.cshtml:18 also renders the badge and is NOT in that list — it has no
    // #nutrient-editor-container at all. So this selector is deliberately not a page-wide
    // one, and if this assertion is ever moved to Review it will match nothing and pass
    // vacuously. Reaching the badge on Review means `#review` or a new container, and the
    // comment has to move with it.
    expect(service.requests).toHaveLength(0);
    await expect(page.locator('#nutrient-editor-container span.badge')).toHaveCount(0);
    await screenshot(page, testInfo, 'service-connection-enrich-no-connection');
  });

  test('should post the chosen model and reasoning effort to the connection when enriching', async ({ page }, testInfo) => {
    // The whole path in one test, because that is what it is for: connect through the
    // form, let the probe verify, choose a model the service listed, and watch the
    // completion arrive at that service carrying the credential and the choice.
    test.setTimeout(90000);

    // The environment gate, and the only skip in this file. It asks the machine, not the
    // app, and it runs first so an offline worker never starts a stub or opens a page.
    const manufacturer = 'https://example.com/';
    test.skip(!(await pageIsReachable(manufacturer)),
      'Skipping — this machine has no route to a public HTTPS page, so the scrape half of '
      + 'this path cannot run. Asked from the test process rather than from the app, because '
      + 'an app that cannot scrape a page the test process just fetched is a product failure '
      + 'and must not report itself as an environment fault. The local half — probe, catalog, '
      + 'picker, model, reasoning effort — is stubbed and is asserted on either way.');

    const service = await startStub();
    const apiKey = 'sk-stub-enrich-1234';

    await page.goto('/ServiceConnection/Index');
    await connectViaForm(page, service.baseUrl, apiKey, 'verified');

    // The picker's dropdown, not the free-text field: `selectOption` throws on anything
    // that is not a <select>, so a probe that stopped listing models fails here rather
    // than quietly saving a model nobody could have picked.
    await page.getByLabel('Model', { exact: true }).selectOption('stub-model-b');
    await page.getByLabel('Reasoning effort').selectOption('high');
    await page.getByRole('button', { name: 'Save model' }).click();
    await expect(page.getByText('Model and reasoning effort saved.')).toBeVisible();
    await expect(page.getByLabel('Model (optional)')).toHaveValue('stub-model-b');

    await page.getByRole('link', { name: 'Supplements' }).click();
    await page.getByRole('link', { name: 'Add New Supplement' }).click();

    await page.fill('input[name="Name"]', 'Stub Enrich Round Trip');
    await page.fill('input[name="Brand"]', 'StubBrand');
    await page.fill('input[name="DailyDose"]', '1 capsule');
    // The one thing a loopback stub cannot stand in for. Enrichment scrapes the
    // manufacturer page before it calls the service, and UrlSafetyValidator refuses
    // anything that is not a public HTTPS address — by design, and pinned by
    // UrlSafetyValidatorTests. So this half of the path needs a real page on the
    // internet, and only this half does: the probe, the catalog and the picker's
    // choices are all local, and the preflight above is the only reason to skip.
    await page.fill('input[name="ManufacturerUrl"]', manufacturer);
    await page.click('button#enrich-btn');

    await expect(page.locator('h4')).toContainText('Nutrients for', { timeout: 60000 });
    // .first() because strict mode throws on a locator that resolves to more than one,
    // and a swap that ever rendered two notes would take this test down with a
    // Playwright error rather than a statement about the app. The code means "the note".
    const note = page.locator('.alert-info').first();
    const noteText = (await note.count()) ? await note.innerText() : '';

    // No note at all, and a failure if there is one. This is the assertion the old
    // network-fault skip was quietly replacing: "Failed to fetch manufacturer page" and
    // "No content found on manufacturer page" are what LlmService returns for a fetch
    // that never landed, but they are ALSO what it returns for a CleanHtml that extracts
    // nothing from a page that loaded, and for a UrlSafetyValidator that blocks the URL.
    // The preflight already settled which of those is the environment's fault, so here
    // every one of them is the app's. The one residual this cannot rule out is
    // example.com answering the preflight and not the app's request; then the fix is a
    // different page, not a quieter test, and the message says which page.
    expect(noteText, `the app could not scrape ${manufacturer}, which the test process had just fetched`).toBe('');

    // What the service was asked for. `model` is the picker's choice and
    // `reasoning_effort` the variant's, lifted onto the wire from the saved row — the
    // whole reason the picker is on this page.
    const completions = service.requests.filter(request => request.method === 'POST');
    expect(completions).toHaveLength(1);
    expect(completions[0].path).toBe('/v1/chat/completions');
    expect(completions[0].headers.authorization).toBe(`Bearer ${apiKey}`);
    expect(completions[0].headers['x-opencode-session']).toBeTruthy();
    // The scraped page travelled in the prompt, so the chain is fetch -> prompt -> post
    // and not a post with an empty context. The two things asserted are the ones this
    // test controls — the form's own name and brand — plus the size of the section the
    // scraped text goes in. What the page says is a third party's copy and is
    // deliberately not pinned: an earlier draft of this assertion matched a sentence
    // example.com used to carry and failed the day it reworded its own homepage, which
    // says nothing about the app.
    const sent = JSON.parse(completions[0].body);
    expect(sent.model).toBe('stub-model-b');
    expect(sent.reasoning_effort).toBe('high');
    const userPrompt = sent.messages[1].content;
    expect(userPrompt).toContain('Stub Enrich Round Trip');
    const scraped = (userPrompt.split('Product Page Content:')[1] ?? '').split('Respond with ONLY')[0];
    expect(scraped.trim().length).toBeGreaterThan(50);

    // And the answer came back through the app's own parser into the editor, by name.
    await expect(page.locator('input[name="nutrients[0].GenericName"]')).toHaveValue('Stub Vitamin C');
    await expect(page.locator('input[name="nutrients[1].GenericName"]')).toHaveValue('Stub Zinc');
    await expect(page.locator('input[name="nutrients[0].Dosage"]')).toHaveValue('80mg');
    await screenshot(page, testInfo, 'service-connection-enriched');
  });
});
